### ISSUE TITLE
Extend BT plugin to support non-SPP connections (e.g., HRM / Cadence)

### ISSUE THREAD

**Issue by rtholmes** [blackberry/WebWorks-Community-APIs#371]
The SimpleBtSppPlugin is a great proof of concept for working with bluetooth from Webworks. Is there any chance it could be extended to support GATT for non-chat applications, or would it be better to start from scratch?. For example, something that would work for the HR / Cadence scenarios here would be fantastic:

http://devblog.blackberry.com/2013/04/bluetooth-low-energy-and-the-internet-of-things/

http://devblog.blackberry.com/2013/05/nfc-cadence-cascades/

**Comment by timwindsor** [comment]
@rtholmes Take a look at https://github.com/blackberry/WebWorks-Community-APIs/tree/master/BB10-Cordova/SimpleBtLeHrPlugin added by #379. Does it do what you need?

**Comment by rtholmes** [comment]
Wow, works great @timwindsor ; thanks so much @jcmurray! This is awesome! Just a quick question: to add cadence, would you recommend just modifying the plugin and adding support for the additional profile, or would you recommend copying and adding the profile to a new plugin?

**Comment by jcmurray** [comment]
For the Cycling Speed and Cadence profile and for a code sample I'd probably clone the HRM plugin and replace the HRM specific parts by the Cadence parts -- 80-90%% of the plugin will be the same since it's really only the format of the characteristics and notification that will carry a different payload that would be different. You should be able to cookie-cutter it. Check out this earlier post on Cadence here: http://devblog.blackberry.com/2013/05/nfc-cadence-cascades/ -- you'll find all the necessary Cadence logic here as well https://github.com/blackberry/Cascades-Community-Samples/tree/master/CscMonitor .
