### ISSUE TITLE
GoogleAnalytics plugin resets UUID

### ISSUE THREAD

**Issue by timwindsor** [blackberry/WebWorks-Community-APIs#376]
In the current version of the plugin in https://github.com/blackberry/GAPlugin, the uuid is being reset here: https://github.com/blackberry/GAPlugin/blob/master/src/blackberry10/index.js#L312

Investigate if this is a merge error or actually has a purpose.

Report of this as an issue is in #375 for context.

**Comment by Bathlamos** [comment]
The line at https://github.com/blackberry/GAPlugin/blob/master/src/blackberry10/index.js#L312 does nothing because the key is the empty string, but is not harmful to the execution of the program.

@analytik: Let me summarize the issue to see if I understand correctly. When you have initialized GAPlugin with a UUID and you want to initialize the plugin again with the empty string in place of a UUID, you expect to see the UUID that was last used substituted for the empty string.

**Comment by analytik** [comment]
Hi Philippe,Yes, that is correct. There is no practical use (that I can think of) for resetting UUID with every app start besides debugging; ‎by resetting UUID, Google Analytics reports wrong number of users.                                                                                                                                                                                                                                                                           Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: Philippe LegaultSent: Saturday, January 17, 2015 11:12 PMTo: blackberry/WebWorks-Community-APIsReply To: blackberry/WebWorks-Community-APIsCc: Milan BSubject: Re: [WebWorks-Community-APIs] GoogleAnalytics plugin resets UUID (#376)The line at https://github.com/blackberry/GAPlugin/blob/master/src/blackberry10/index.js#L312 does nothing because the key is the empty string, but is not harmful to the execution of the program.

@analytik: Let me summarize the issue to see if I understand correctly. When you have initialized GAPlugin with a UUID and you want to initialize the plugin again with the empty string in place of a UUID, you expect to see the UUID that was last used substituted for the empty string.

—Reply to this email directly or view it on GitHub.

**Comment by Bathlamos** [comment]
This bug has been addressed. Can you confirm that it works for you please? I will close the bug afterwards.
