### ISSUE TITLE
Barcode Scanner: Which ZXing Code is being used?

### ISSUE THREAD

**Issue by mattgrande** [blackberry/WebWorks-Community-APIs#381]
Hi there,

For the Barcode Scanner, the scanning seems to be passed off to ZXing, although I'm not sure where the code is... I'm worried because in the iOS version of the scanner, the [validate quiet zone function is commented out for seemingly no reason](https://github.com/wildabeast/BarcodeScanner/issues/224). I'm getting similar results in Blackberry (the quiet zone not being respected), and I'd like to verify if it's the same issue.

**Comment by timwindsor** [comment]
In our current version, we're using the library that is built into BlackBerry 10. That version is pretty old: [2.2](https://github.com/blackberry/zxing). It should be relatively easy to build in an .so of the latest ZXing with any modifications you wanted and make it use that version. Statically linking if necessary should be fine too since the license is the same.

That said, it doesn't appear as though it's commented out in our code:
https://github.com/blackberry/zxing/blob/master/cpp/core/src/zxing/oned/ITFReader.cpp#L232-L245

**Comment by mattgrande** [comment]
Looks like it was commented out until April 1, 2013, though (https://github.com/blackberry/zxing/commit/fab4bb096714525eec415a5c239a1e83a0012429).

My C++ is pretty weak (haven't really touched the language in years), but I can take a look at building it in, I guess.

**Comment by timwindsor** [comment]
Added building in a new version of ZXing to the list here: #386
