### ISSUE TITLE
Investigate running PouchDB on BlackBerry 10

### ISSUE THREAD

**Issue by timwindsor** [blackberry/WebWorks-Community-APIs#382]
Test out PouchDB to see what, if anything, needs to be done to make it work on BlackBerry 10's browser. The aim is to have it supported, as a stepping stone to getting CouchDB Lite support using a JavaScript interface.

https://github.com/pouchdb/pouchdb

**Comment by umcsdon** [comment]
Tried it using this example: https://github.com/vmcampos/pouchdb-phonegap

I have to download all required css and javascript to local directory (cdn not working for me); otherwise, "quota" problem arise.

The data can be inserted into database, but I do see "conflict 409" error in the console. (Could be problem related to the example source code)

The *Official* example works perfectly (no errors or warnings).
https://github.com/pouchdb/pouchdb/wiki/PouchDB-on-Phonegap

**Comment by rtholmes** [comment]
Hi @umcsdon, did you happen to check to see what the maximum data storage limit is for a PouchDB instance is on BB10? This isn't in the official PouchDB docs either and would be interesting to know.

**Comment by umcsdon** [comment]
Hi @rtholmes 

I didn't check the upper limit yet, will do it this weekend.

**Comment by umcsdon** [comment]
Hi @rtholmes 

BB10 uses either IndexedDB or WebSQL based on this document [(link)](http://pouchdb.com/adapters.html)

Then, I created a testing cordova application. It will open a website described [here](http://www.html5rocks.com/en/tutorials/offline/quota-research/).

WebSQL allows me to store 500MB+ (maybe unlimted???)

**Comment by timwindsor** [comment]
That's very positive. It's probably not artificially limited, but I can't remember.

**Comment by umcsdon** [comment]
What is the expectation of this issue? A fully working sample cordova application?

**Comment by timwindsor** [comment]
I think that would be good. Just a proof of concept, as we are using this as a stepping stone to get a Couchbase plugin working. We could potentially use the same test app with that.

**Comment by rtholmes** [comment]
I still seem to be limited to 10 MB in the pouch instance; have you tried to store more than that?

**Comment by rtholmes** [comment]
Looking at this further I think this is because the Cordova SQLite plugin (http://plugins.cordova.io/#/package/com.triarc.sqliteplugin) does not seem to support BB10 which results in the size limitation.

**Comment by umcsdon** [comment]
Hi @rtholmes, I tested using [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) which is a dependency for phonegap Todo Lite sample described [here](https://github.com/couchbaselabs/TodoLite-PhoneGap).

**Comment by umcsdon** [comment]
It's possible to use webSQL or IndexedDB as described in the [cordova documentation](http://cordova.apache.org/docs/en/5.0.0/cordova_storage_storage.md.html#Storage).

**Comment by rtholmes** [comment]
Thanks for the links @umcsdon . Unfortunately, the IndexedDB adapter does not work with BlackBerry10 (```Error_Adapter is missing```) and the WebSQL adapter is limited to 10MB. The last link requires the SQLite plugin to actually store more than 10MB on BB10, but again this is also not supported.

If I'm mistaken and you have managed to store > 10 MB, please let me know. Otherwise we'll write this up as a platform limitation until the SQLite plugin is ported (or the ```size``` attribute for WebSQL adapter is supported). 

Using IndexedDB: 
```return new PouchDB('tileDB', {adapter: 'idb'}); // doesn't work, 'Error_Adapter is missing' on save```

Using WebSQL: 
```return new PouchDB('tileDB',{adapter: 'websql', size: 100}); // 10 MB limit, size not honoured```

**Comment by umcsdon** [comment]
Sounds good to me.

**Comment by rtholmes** [comment]
Just another note @timwindsor: This might be fixed in an upcoming PouchDB commit (hopefully will be in v3.5):  https://github.com/pouchdb/pouchdb/pull/3737

**Comment by timwindsor** [comment]
Excellent.

**Comment by rtholmes** [comment]
PouchDB 3.5 has been released now. It turns out while IndexDB is being used now, the DB size limit is still 10MB (even if the size: attribute is provided).

**Comment by timwindsor** [comment]
Closing here and moved to the sample repo
